### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by Yajo** [flathub/org.cockpit_project.CockpitClient#2]
I can't use the app.

1. Open it.
2. Write the ssh connection parameters.
3. Connect to the server (it has `cockpit-bridge` installed).
4. ![imagen](https://user-images.githubusercontent.com/973709/147745119-c5be9394-c511-4570-a501-af0a42e3a849.png)

😭 What am I doing wrong?

**Comment by martinpitt** [comment]
The server also needs at least cockpit-system installed. That will remedy the "not found" issue. Depending on which pages you want to use, you may want to install further packages, such as cockpit-{networkmanager,podman,machines,...}

**Comment by allisonkarlitskaya** [comment]
hello @Yajo thanks for the report.

@pitti is correct about the solution to this problem, but I think there's an actual bug here.  This "Not found" page is confusing, and doesn't provide enough help about what the problem is.

I've opened cockpit-project/cockpit#16775 to track this (and hopefully improve it).

Thanks again, and happy new year!
